#name: 'Production Preview: Build and Deploy to S3'
#permissions:
#  id-token: write
#
#env:
#  ARTIFACT_NAME: ${{ vars.ARTIFACT_NAME }}
#  BUILD_CACHE_ID: tpp-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
#
#on:
#  push:
#    branches: [ 'master' ]
#    paths: ['pulter-site/**', 'pulter-poems/**']
#  workflow_dispatch:
#
#jobs:
#  build-and-deploy:
#    runs-on: macos-latest
#    steps:
#      - name: Output Run ID
#        run: echo ${{ github.run_id }}
#      - name: Output Run Number
#        run: echo ${{ github.run_number }}
#      - name: Output Run Attempt
#        run: echo ${{ github.run_attempt }}
#      - name: Output Build Cache Id
#        run: echo $BUILD_CACHE_ID
#
#      - name: Check out the repo
#        uses: actions/checkout@v1
#        with:
#          submodules: true
#
#      - name: Prepare Node 20
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20.x'
#
#      - name: Install packages
#        run: yarn
#
#      - name: Install task runner
#        run: npm i -g gulp-cli@latest
#
#      - name: Build the site
#        run: npm run build
#
#      - name: Import Secrets
#        id: import-secrets
#        uses: hashicorp/vault-action@v2
#        with:
#          url: https://vault.weinberg.northwestern.edu:443
#          role: MADS-S3-dev
#          path: jwt-github
#          method: jwt
#          secrets: |
#            platforms-kvv2/data/secrets/MADS-S3/pulterproject-staging access_key | AWS_ACCESS_KEY_ID ;
#            platforms-kvv2/data/secrets/MADS-S3/pulterproject-staging secret_key | AWS_SECRET_ACCESS_KEY ;
#
#      - name: Deploy to S3
#        id: sync
#        run: aws s3 sync dist/ s3://$BUCKET_NAME --delete
#        env:
#          AWS_ACCESS_KEY_ID: "${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}"
#          AWS_SECRET_ACCESS_KEY: "${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"
#          AWS_DEFAULT_REGION: us-east-2
#          BUCKET_NAME: "mads-static-sites-staging-pulterproject-staging"
#
