name: 'Production Preview: Build and Deploy to S3'

on:
  push:
    branches: [ 'master' ]
    paths: ['pulter-site/**', 'pulter-poems/**']

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Prepare Node 20
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install packages
        run: yarn

      - name: Install Gulp
        run: npm i -g gulp-cli@latest

      - name: Build the site
        run: npm run build

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.weinberg.northwestern.edu:443
          role: MADS-S3-dev
          path: jwt-github-mads
          method: jwt
          secrets: |
            platforms-kvv2/data/secrets/MADS-S3/dev access_key | AWS_ACCESS_KEY_ID ;
            platforms-kvv2/data/secrets/MADS-S3/dev secret_key | AWS_SECRET_ACCESS_KEY ;

      - name: Deploy to S3
        id: sync
        run: aws s3 sync dist/ s3://$BUCKET_NAME --delete
        env:
          AWS_ACCESS_KEY_ID: "${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"
          AWS_DEFAULT_REGION: us-east-2
          BUCKET_NAME: "mads-static-sites-dev-pulterproject-dev"

#      - name: Get CF Dist ID
#        id: get_dist_id
#        env:
#          AWS_ACCESS_KEY_ID: "${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}"
#          AWS_SECRET_ACCESS_KEY: "${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"
#          AWS_DEFAULT_REGION: us-east-2
#          BUCKET_NAME: "mads-static-sites-dev-pulterproject-dev"
#        run: |
#          echo "cf_dist_id=$(aws ssm get-parameter --name /platforms/mads-static-sites/dev/${BUCKET_NAME}/CF_dist --output json | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
#
#      - name: Invalidate CF cache
#        id: invalidate
#        run: aws cloudfront create-invalidation --distribution-id ${{ env.cf_dist_id }} --paths "/*"
#        env:
#          AWS_ACCESS_KEY_ID: "${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}"
#          AWS_SECRET_ACCESS_KEY: "${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"
#          AWS_DEFAULT_REGION: us-east-2
#          BUCKET_NAME: "mads-static-sites-dev-pulterproject-dev"
#        timeout-minutes: 5
